### ISSUE TITLE
Question & Suggestion

### ISSUE THREAD

**Issue by oleggrishechkin** [maverick-js/scheduler#1]
Hi, @mihar-22 
I'm review your code and I can't understand why you do this:

```
do {
    for (const task of queue) {
        task();
        served.add(task);
        queue.delete(task);
    }
} while (queue.size > 0);

served.clear();
```

instead of this:

```
for (const task of queue) {
        task();
}

queue = new Set();
```

In depended code you use served.has(...), but you can use queue.has(...) instead in my suggestion.

Looks the same but "for of" without .add and .delete much faster.

Do I miss something important?

**Comment by mihar-22** [comment]
Hey @oleggrishechkin that area needs a rewrite. I'm trying to ensure:

1. Additional tasks added during a flush are not lost (currently I believe they are)
2. Prevent infinite loop

We satisfy 2 right now but I don't believe we have solved 1.

**Comment by mihar-22** [comment]
You're right that in the current code we can just delete everything and just use the `queue` set. I'm not sure if we can ensure constraint 1. mentioned above with a single set though.

**Comment by oleggrishechkin** [comment]
What problem with 1? 
"for of" will run for all Set items even the new added items while "for of" running.

**Comment by mihar-22** [comment]
Ah don't worry I was thinking about something related to the Maverick Observables library but it might be fine. I was worried that the same task with same reference (unique function) won't be included in the set and run (because it's already in the set). I realized it doesn't matter, my bad.

I'll clean up the implementation some time tomorrow. Thanks @oleggrishechkin!
